import { Niconne } from "next/font/google";

import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

const niconne = Niconne({
  weight: "400", // Niconne only has regular (400) weight
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en" className={`${niconne.variable} ${poppins.variable}`}>
      <body>{children}</body>
    </html>
  );
}
